name: User Service CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  DOTNET_VERSION: '9.0.x'                   

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: |
         cd Backend/UserService/UserService
         dotnet restore

      - name: Build project
        run: |
         cd Backend/UserService/UserService
         dotnet build
          
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
           context: ./UserService/UserService
           dockerfile: Dockerfile
           push: false
           tags: ${{ secrets.DOCKER_HUB_USERNAME }}/user-service:latest
           
           
      - name: login to docker hub
        uses: docker/login-action@v3
        with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push image
        uses: docker/build-push-action@v5
        with:
           context: ./UserService/UserService
           dockerfile: Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/user-service:latest